// @generated by scripts/contracts/generate.mjs; do not edit.

// source_schema_sha256: 98488e9d943aa128c686472788c32db6a65f4f4ec621e7bbc27385e766aa9188

use serde::{Deserialize, Serialize};

pub const SCHEMA_VERSION: &str = "0.1.0";

pub const SOURCE_SCHEMA_SHA256: &str =
    "98488e9d943aa128c686472788c32db6a65f4f4ec621e7bbc27385e766aa9188";

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum EngineKind {
    Chromium,
    Native,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum DataClassification {
    Public,
    Tenant,
    Sensitive,
    Restricted,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum CommandKind {
    SessionCreateV1,
    NavigationGotoV1,
    DomSemanticQueryV1,
    InteractionClickV1,
    SessionCloseV1,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum OutcomeStatus {
    Succeeded,
    Failed,
    Cancelled,
    DeadlineExceeded,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum CapabilityStatus {
    Native,
    NativeLimited,
    Hybrid,
    Chromium,
    Experimental,
    Unsupported,
    DisabledByPolicy,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum CanonicalErrorCode {
    InvalidArgument,
    Unauthenticated,
    PermissionDenied,
    PolicyDenied,
    QuotaExceeded,
    RateLimited,
    SessionNotReady,
    SessionClosed,
    SessionExpired,
    CapacityUnavailable,
    WorkerLost,
    CommandCancelled,
    DeadlineExceeded,
    UnsupportedCapability,
    CapabilityDisabled,
    RendererRequired,
    FallbackProhibited,
    MigrationFailed,
    StateTransferPartial,
    InvalidUrl,
    NetworkPolicyBlocked,
    NavigationFailed,
    SelectorInvalid,
    ElementNotFound,
    ElementAmbiguous,
    ElementNotInteractable,
    ActionPostconditionFailed,
    WorkflowInvalid,
    ApprovalRequired,
    SecretUnavailable,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum EventType {
    SessionLifecycleV1,
    NavigationLifecycleV1,
    NetworkRequestV1,
    NetworkResponseV1,
    ScriptConsoleV1,
    ScriptErrorV1,
    DomRevisionV1,
    InteractionVerifiedV1,
    CapabilityDecisionV1,
    WorkflowApprovalV1,
    ResourceHealthV1,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum EnginePolicy {
    NativeOnly,
    PreferNative,
    PreferCompatible,
    ChromiumOnly,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum FidelityProfile {
    Extract,
    Agent,
    Test,
    Visual,
    Custom,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum WaitUntil {
    Commit,
    Domcontentloaded,
    Load,
    Networkidle,
}

impl EnginePolicy {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::NativeOnly => "native-only",
            Self::PreferNative => "prefer-native",
            Self::PreferCompatible => "prefer-compatible",
            Self::ChromiumOnly => "chromium-only",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "native-only" => Some(Self::NativeOnly),
            "prefer-native" => Some(Self::PreferNative),
            "prefer-compatible" => Some(Self::PreferCompatible),
            "chromium-only" => Some(Self::ChromiumOnly),
            _ => None,
        }
    }
}

impl FidelityProfile {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Extract => "extract",
            Self::Agent => "agent",
            Self::Test => "test",
            Self::Visual => "visual",
            Self::Custom => "custom",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "extract" => Some(Self::Extract),
            "agent" => Some(Self::Agent),
            "test" => Some(Self::Test),
            "visual" => Some(Self::Visual),
            "custom" => Some(Self::Custom),
            _ => None,
        }
    }
}

impl WaitUntil {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Commit => "commit",
            Self::Domcontentloaded => "domcontentloaded",
            Self::Load => "load",
            Self::Networkidle => "networkidle",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "commit" => Some(Self::Commit),
            "domcontentloaded" => Some(Self::Domcontentloaded),
            "load" => Some(Self::Load),
            "networkidle" => Some(Self::Networkidle),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct CommandMetadata {
    pub correlation_id: String,
    pub causation_id: Option<String>,
    pub client: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct SessionCreatePayload {
    pub engine_policy: String,
    pub fidelity_profile: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct NavigationGotoPayload {
    pub url: String,
    pub wait_until: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct SemanticQueryPayload {
    pub query: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ClickPayload {
    pub selector: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct SessionClosePayload {
    pub reason: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct EngineExecution {
    pub requested_engine_policy: String,
    pub engine: EngineKind,
    pub engine_version: String,
    pub capability_snapshot: String,
    pub fallback_used: bool,
    pub fallback_reason: Option<String>,
    pub migration_id: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct CanonicalError {
    pub code: CanonicalErrorCode,
    pub category: String,
    pub message: String,
    pub retryable: bool,
    pub retry_after_ms: Option<u64>,
    pub engine: Option<EngineKind>,
    pub capability: Option<String>,
    pub command_id: String,
    pub correlation_id: String,
    pub details: serde_json::Value,
    pub cause_code: Option<CanonicalErrorCode>,
    pub documentation_ref: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct CommandOutcome {
    pub command_id: String,
    pub attempt: u64,
    pub status: OutcomeStatus,
    pub result: Option<String>,
    pub error: Option<CanonicalError>,
    pub execution: EngineExecution,
    pub trace_ref: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct EventEnvelope {
    pub event_id: String,
    pub sequence: u64,
    pub event_type: EventType,
    pub session_id: String,
    pub context_id: Option<String>,
    pub page_id: Option<String>,
    pub command_id: Option<String>,
    pub timestamp: String,
    pub correlation_id: String,
    pub engine: EngineKind,
    pub payload: String,
    pub classification: DataClassification,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct CapabilityStatusRecord {
    pub capability_id: String,
    pub status: CapabilityStatus,
    pub engine_build: String,
    pub protocol_surfaces: Vec<String>,
    pub limitations: Vec<String>,
    pub last_verified: Option<String>,
    pub owner: String,
}

impl SessionCreatePayload {
    pub fn engine_policy_kind(&self) -> Option<EnginePolicy> {
        EnginePolicy::parse(&self.engine_policy)
    }
}

impl SessionCreatePayload {
    pub fn fidelity_profile_kind(&self) -> Option<FidelityProfile> {
        FidelityProfile::parse(&self.fidelity_profile)
    }
}

impl NavigationGotoPayload {
    pub fn wait_until_kind(&self) -> Option<WaitUntil> {
        self.wait_until.as_deref().and_then(WaitUntil::parse)
    }
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum CommandPayload {
    SessionCreate(SessionCreatePayload),
    NavigationGoto(NavigationGotoPayload),
    SemanticQuery(SemanticQueryPayload),
    Click(ClickPayload),
    SessionClose(SessionClosePayload),
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct CommandEnvelope {
    pub command_id: String,
    pub session_id: String,
    pub context_id: Option<String>,
    pub page_id: Option<String>,
    pub kind: CommandKind,
    pub payload: CommandPayload,
    pub idempotency_key: Option<String>,
    pub deadline_ms: u64,
    pub required_capabilities: Vec<String>,
    pub metadata: CommandMetadata,
}

impl CommandPayload {
    pub const fn kind(&self) -> CommandKind {
        match self {
            Self::SessionCreate(_) => CommandKind::SessionCreateV1,
            Self::NavigationGoto(_) => CommandKind::NavigationGotoV1,
            Self::SemanticQuery(_) => CommandKind::DomSemanticQueryV1,
            Self::Click(_) => CommandKind::InteractionClickV1,
            Self::SessionClose(_) => CommandKind::SessionCloseV1,
        }
    }

    pub fn matches_kind(&self, kind: CommandKind) -> bool {
        self.kind() == kind
    }
}

impl CommandEnvelope {
    pub fn payload_matches_kind(&self) -> bool {
        self.payload.matches_kind(self.kind)
    }
}
