// @generated by scripts/contracts/generate.mjs; do not edit.

// source_schema_sha256: 634beb757d2245b858b3c36b6c51cb60f91e3266ed46b2f578517a15da58d686

pub const SCHEMA_VERSION: &str = "0.1.0";

pub const SOURCE_SCHEMA_SHA256: &str =
    "634beb757d2245b858b3c36b6c51cb60f91e3266ed46b2f578517a15da58d686";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EngineKind {
    Chromium,
    Native,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DataClassification {
    Public,
    Tenant,
    Sensitive,
    Restricted,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CommandKind {
    SessionCreateV1,
    NavigationGotoV1,
    DomSemanticQueryV1,
    InteractionClickV1,
    SessionCloseV1,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum OutcomeStatus {
    Succeeded,
    Failed,
    Cancelled,
    DeadlineExceeded,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityStatus {
    Native,
    NativeLimited,
    Hybrid,
    Chromium,
    Experimental,
    Unsupported,
    DisabledByPolicy,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CanonicalErrorCode {
    InvalidArgument,
    Unauthenticated,
    PermissionDenied,
    PolicyDenied,
    QuotaExceeded,
    RateLimited,
    SessionNotReady,
    SessionClosed,
    SessionExpired,
    CapacityUnavailable,
    WorkerLost,
    CommandCancelled,
    DeadlineExceeded,
    UnsupportedCapability,
    CapabilityDisabled,
    RendererRequired,
    FallbackProhibited,
    MigrationFailed,
    StateTransferPartial,
    InvalidUrl,
    NetworkPolicyBlocked,
    NavigationFailed,
    SelectorInvalid,
    ElementNotFound,
    ElementAmbiguous,
    ElementNotInteractable,
    ActionPostconditionFailed,
    WorkflowInvalid,
    ApprovalRequired,
    SecretUnavailable,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum EventType {
    SessionLifecycleV1,
    NavigationLifecycleV1,
    NetworkRequestV1,
    NetworkResponseV1,
    ScriptConsoleV1,
    ScriptErrorV1,
    DomRevisionV1,
    InteractionVerifiedV1,
    CapabilityDecisionV1,
    WorkflowApprovalV1,
    ResourceHealthV1,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommandMetadata {
    pub correlation_id: String,
    pub causation_id: Option<String>,
    pub client: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SessionCreatePayload {
    pub engine_policy: String,
    pub fidelity_profile: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NavigationGotoPayload {
    pub url: String,
    pub wait_until: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SemanticQueryPayload {
    pub query: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ClickPayload {
    pub selector: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SessionClosePayload {
    pub reason: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EngineExecution {
    pub requested_engine_policy: String,
    pub engine: EngineKind,
    pub engine_version: String,
    pub capability_snapshot: String,
    pub fallback_used: bool,
    pub fallback_reason: Option<String>,
    pub migration_id: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CanonicalError {
    pub code: CanonicalErrorCode,
    pub category: String,
    pub message: String,
    pub retryable: bool,
    pub retry_after_ms: Option<u64>,
    pub engine: Option<EngineKind>,
    pub capability: Option<String>,
    pub command_id: String,
    pub correlation_id: String,
    pub details: String,
    pub cause_code: Option<CanonicalErrorCode>,
    pub documentation_ref: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommandOutcome {
    pub command_id: String,
    pub attempt: u64,
    pub status: OutcomeStatus,
    pub result: Option<String>,
    pub error: Option<CanonicalError>,
    pub execution: EngineExecution,
    pub trace_ref: Option<String>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EventEnvelope {
    pub event_id: String,
    pub sequence: u64,
    pub event_type: EventType,
    pub session_id: String,
    pub context_id: Option<String>,
    pub page_id: Option<String>,
    pub command_id: Option<String>,
    pub timestamp: String,
    pub correlation_id: String,
    pub engine: EngineKind,
    pub payload: String,
    pub classification: DataClassification,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CapabilityStatusRecord {
    pub capability_id: String,
    pub status: CapabilityStatus,
    pub engine_build: String,
    pub protocol_surfaces: Vec<String>,
    pub limitations: Vec<String>,
    pub last_verified: Option<String>,
    pub owner: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum CommandPayload {
    SessionCreate(SessionCreatePayload),
    NavigationGoto(NavigationGotoPayload),
    SemanticQuery(SemanticQueryPayload),
    Click(ClickPayload),
    SessionClose(SessionClosePayload),
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct CommandEnvelope {
    pub command_id: String,
    pub session_id: String,
    pub context_id: Option<String>,
    pub page_id: Option<String>,
    pub kind: CommandKind,
    pub payload: CommandPayload,
    pub idempotency_key: Option<String>,
    pub deadline_ms: u64,
    pub required_capabilities: Vec<String>,
    pub metadata: CommandMetadata,
}
