// @generated by scripts/contracts/generate.mjs; do not edit.

// source_schema_sha256: 98488e9d943aa128c686472788c32db6a65f4f4ec621e7bbc27385e766aa9188

export const SCHEMA_VERSION = "0.1.0" as const;

export const SOURCE_SCHEMA_SHA256 = "98488e9d943aa128c686472788c32db6a65f4f4ec621e7bbc27385e766aa9188" as const;

export enum EngineKind {
  chromium = "chromium",
  native = "native",
}

export enum DataClassification {
  public = "public",
  tenant = "tenant",
  sensitive = "sensitive",
  restricted = "restricted",
}

export enum CommandKind {
  sessionCreateV1 = "session.create.v1",
  navigationGotoV1 = "navigation.goto.v1",
  domSemanticQueryV1 = "dom.semantic_query.v1",
  interactionClickV1 = "interaction.click.v1",
  sessionCloseV1 = "session.close.v1",
}

export enum OutcomeStatus {
  succeeded = "succeeded",
  failed = "failed",
  cancelled = "cancelled",
  deadlineExceeded = "deadline_exceeded",
}

export enum CapabilityStatus {
  native = "native",
  nativeLimited = "native-limited",
  hybrid = "hybrid",
  chromium = "chromium",
  experimental = "experimental",
  unsupported = "unsupported",
  disabledByPolicy = "disabled-by-policy",
}

export enum CanonicalErrorCode {
  invalidArgument = "INVALID_ARGUMENT",
  unauthenticated = "UNAUTHENTICATED",
  permissionDenied = "PERMISSION_DENIED",
  policyDenied = "POLICY_DENIED",
  quotaExceeded = "QUOTA_EXCEEDED",
  rateLimited = "RATE_LIMITED",
  sessionNotReady = "SESSION_NOT_READY",
  sessionClosed = "SESSION_CLOSED",
  sessionExpired = "SESSION_EXPIRED",
  capacityUnavailable = "CAPACITY_UNAVAILABLE",
  workerLost = "WORKER_LOST",
  commandCancelled = "COMMAND_CANCELLED",
  deadlineExceeded = "DEADLINE_EXCEEDED",
  unsupportedCapability = "UNSUPPORTED_CAPABILITY",
  capabilityDisabled = "CAPABILITY_DISABLED",
  rendererRequired = "RENDERER_REQUIRED",
  fallbackProhibited = "FALLBACK_PROHIBITED",
  migrationFailed = "MIGRATION_FAILED",
  stateTransferPartial = "STATE_TRANSFER_PARTIAL",
  invalidUrl = "INVALID_URL",
  networkPolicyBlocked = "NETWORK_POLICY_BLOCKED",
  navigationFailed = "NAVIGATION_FAILED",
  selectorInvalid = "SELECTOR_INVALID",
  elementNotFound = "ELEMENT_NOT_FOUND",
  elementAmbiguous = "ELEMENT_AMBIGUOUS",
  elementNotInteractable = "ELEMENT_NOT_INTERACTABLE",
  actionPostconditionFailed = "ACTION_POSTCONDITION_FAILED",
  workflowInvalid = "WORKFLOW_INVALID",
  approvalRequired = "APPROVAL_REQUIRED",
  secretUnavailable = "SECRET_UNAVAILABLE",
}

export enum EventType {
  sessionLifecycleV1 = "session.lifecycle.v1",
  navigationLifecycleV1 = "navigation.lifecycle.v1",
  networkRequestV1 = "network.request.v1",
  networkResponseV1 = "network.response.v1",
  scriptConsoleV1 = "script.console.v1",
  scriptErrorV1 = "script.error.v1",
  domRevisionV1 = "dom.revision.v1",
  interactionVerifiedV1 = "interaction.verified.v1",
  capabilityDecisionV1 = "capability.decision.v1",
  workflowApprovalV1 = "workflow.approval.v1",
  resourceHealthV1 = "resource.health.v1",
}

export enum EnginePolicy {
  nativeOnly = "native-only",
  preferNative = "prefer-native",
  preferCompatible = "prefer-compatible",
  chromiumOnly = "chromium-only",
}

export enum FidelityProfile {
  extract = "extract",
  agent = "agent",
  test = "test",
  visual = "visual",
  custom = "custom",
}

export enum WaitUntil {
  commit = "commit",
  domcontentloaded = "domcontentloaded",
  load = "load",
  networkidle = "networkidle",
}

export interface CommandMetadata {
  correlation_id: string;
  causation_id?: string;
  client: string;
}

export interface SessionCreatePayload {
  engine_policy: EnginePolicy;
  fidelity_profile: FidelityProfile;
}

export interface NavigationGotoPayload {
  url: string;
  wait_until?: WaitUntil;
}

export interface SemanticQueryPayload {
  query: string;
}

export interface ClickPayload {
  selector: string;
}

export interface SessionClosePayload {
  reason?: string;
}

export interface EngineExecution {
  requested_engine_policy: string;
  engine: EngineKind;
  engine_version: string;
  capability_snapshot: string;
  fallback_used: boolean;
  fallback_reason?: string;
  migration_id?: string;
}

export interface CanonicalError {
  code: CanonicalErrorCode;
  category: string;
  message: string;
  retryable: boolean;
  retry_after_ms?: number;
  engine?: EngineKind;
  capability?: string;
  command_id: string;
  correlation_id: string;
  details: Record<string, unknown>;
  cause_code?: CanonicalErrorCode;
  documentation_ref: string;
}

export interface CommandOutcome {
  command_id: string;
  attempt: number;
  status: OutcomeStatus;
  result?: string;
  error?: CanonicalError;
  execution: EngineExecution;
  trace_ref?: string;
}

export interface EventEnvelope {
  event_id: string;
  sequence: number;
  event_type: EventType;
  session_id: string;
  context_id?: string;
  page_id?: string;
  command_id?: string;
  timestamp: string;
  correlation_id: string;
  engine: EngineKind;
  payload: string;
  classification: DataClassification;
}

export interface CapabilityStatusRecord {
  capability_id: string;
  status: CapabilityStatus;
  engine_build: string;
  protocol_surfaces: string[];
  limitations: string[];
  last_verified?: string;
  owner: string;
}

export type CommandPayload =
  | SessionCreatePayload
  | NavigationGotoPayload
  | SemanticQueryPayload
  | ClickPayload
  | SessionClosePayload;

export interface CommandPayloadByKind {
  [CommandKind.sessionCreateV1]: SessionCreatePayload;
  [CommandKind.navigationGotoV1]: NavigationGotoPayload;
  [CommandKind.domSemanticQueryV1]: SemanticQueryPayload;
  [CommandKind.interactionClickV1]: ClickPayload;
  [CommandKind.sessionCloseV1]: SessionClosePayload;
}

export type CommandPayloadFor<Kind extends CommandKind> = CommandPayloadByKind[Kind];

export interface CommandEnvelopeBase {
  command_id: string;
  session_id: string;
  context_id?: string;
  page_id?: string;
  idempotency_key?: string;
  deadline_ms: number;
  required_capabilities: string[];
  metadata: CommandMetadata;
}

export type CommandEnvelope =
  | CommandEnvelopeBase & { kind: CommandKind.sessionCreateV1; payload: SessionCreatePayload }
  | CommandEnvelopeBase & { kind: CommandKind.navigationGotoV1; payload: NavigationGotoPayload }
  | CommandEnvelopeBase & { kind: CommandKind.domSemanticQueryV1; payload: SemanticQueryPayload }
  | CommandEnvelopeBase & { kind: CommandKind.interactionClickV1; payload: ClickPayload }
  | CommandEnvelopeBase & { kind: CommandKind.sessionCloseV1; payload: SessionClosePayload };
