//! The WHATWG "special" element category (§13.2.4.2), used by the "any
//! other end tag" algorithm and the adoption agency algorithm's furthest-
//! block search. Representative, not exhaustive for the rarely-used
//! foreign-content entries (documented, matches the rest of this crate's
//! MVP foreign-content scope — see `foreign.rs`).
use machina_dom::Namespace;

const SPECIAL_HTML_TAGS: &[&str] = &[
    "address",
    "applet",
    "area",
    "article",
    "aside",
    "base",
    "basefont",
    "bgsound",
    "blockquote",
    "body",
    "br",
    "button",
    "caption",
    "center",
    "col",
    "colgroup",
    "dd",
    "details",
    "dir",
    "div",
    "dl",
    "dt",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "form",
    "frame",
    "frameset",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "iframe",
    "img",
    "input",
    "keygen",
    "li",
    "link",
    "listing",
    "main",
    "marquee",
    "menu",
    "meta",
    "nav",
    "noembed",
    "noframes",
    "noscript",
    "object",
    "ol",
    "p",
    "param",
    "plaintext",
    "pre",
    "script",
    "search",
    "section",
    "select",
    "source",
    "style",
    "summary",
    "table",
    "tbody",
    "td",
    "template",
    "textarea",
    "tfoot",
    "th",
    "thead",
    "title",
    "tr",
    "track",
    "ul",
    "wbr",
    "xmp",
];

const SPECIAL_MATHML_TAGS: &[&str] = &["mi", "mo", "mn", "ms", "mtext", "annotation-xml"];
const SPECIAL_SVG_TAGS: &[&str] = &["foreignObject", "desc", "title"];

pub(crate) fn is_special(tag: &str, namespace: Namespace) -> bool {
    match namespace {
        Namespace::Html => SPECIAL_HTML_TAGS.contains(&tag),
        Namespace::MathMl => SPECIAL_MATHML_TAGS.contains(&tag),
        Namespace::Svg => SPECIAL_SVG_TAGS.contains(&tag),
    }
}
